In [5]:
from sklearn.datasets import make_classification
import torch

In [9]:
#step01 : creating s synthetic dataset

X , y = make_classification(n_samples=10, n_features=2, n_redundant=0, n_classes=2, random_state=42)

In [13]:
X.shape , y.shape

((10, 2), (10,))

In [20]:
X_tensor = torch.tensor(X,dtype=torch.float32)
y_tensor = torch.tensor(y,dtype=torch.long)

In [21]:
from torch.utils.data import Dataset, DataLoader

In [23]:
class custom_dataset(Dataset):
    
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels
        
    def __len__(self):
        
        return self.features.shape[0]
    
    def __getitem__(self,index):
        
        return self.features[index] , self.labels[index]

In [ ]:
dataset = custom_dataset(X_tensor,y_tensor) #object

In [26]:
len(dataset)

10

In [27]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [28]:
dataloader = DataLoader(dataset=dataset, batch_size=2, shuffle=True)

In [30]:
for batch_feature,batch_labels in dataloader:
    print(batch_feature)
    print(batch_labels)
    print("==="*20)

tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]])
tensor([1, 0])
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1, 1])
tensor([[-2.8954,  1.9769],
        [-1.9629, -0.9923]])
tensor([0, 0])
tensor([[ 1.0683, -0.9701],
        [ 1.8997,  0.8344]])
tensor([1, 1])
tensor([[-1.1402, -0.8388],
        [-0.7206, -0.9606]])
tensor([0, 0])
