In [2]:
import torch
import torch.nn as nn


In [43]:
#making a model
class Model(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
        
    def forward(self,feature):
        
        y_pred = self.network(feature)
        
        return y_pred

In [44]:
#dataset
features = torch.randn(10,5)

#model

model = Model(features.shape[1])

#call model for forward pass

y_pred = model(features)

In [45]:
y_pred

tensor([[0.4680],
        [0.4723],
        [0.3926],
        [0.4443],
        [0.4732],
        [0.4163],
        [0.5229],
        [0.4610],
        [0.4208],
        [0.4371]], grad_fn=<SigmoidBackward0>)

In [46]:
y_pred.shape

torch.Size([10, 1])

In [47]:
model.network[0].weight , model.network[2].weight , model.network[1]

(Parameter containing:
 tensor([[ 0.0548, -0.4106, -0.3837,  0.4344, -0.1656],
         [-0.2963, -0.0815,  0.1734, -0.0956, -0.1254],
         [ 0.3495, -0.2723,  0.4014,  0.0264, -0.0499]], requires_grad=True),
 Parameter containing:
 tensor([[0.2671, 0.5157, 0.2439]], requires_grad=True),
 ReLU())

In [13]:
model.sigmoid

Sigmoid()

In [48]:
from torchinfo import summary

In [51]:
summary(model,input_size=(features.shape[0],features.shape[1]),depth=2)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00