In [98]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch 
import torch.nn as nn

In [78]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [79]:
df.columns.values

array(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean',
       'concavity_mean', 'concave points_mean', 'symmetry_mean',
       'fractal_dimension_mean', 'radius_se', 'texture_se',
       'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se',
       'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype=object)

In [80]:
df.shape

(569, 33)

In [81]:
df.drop(columns = ['Unnamed: 32','id'], inplace = True)

In [82]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [83]:
y = df['diagnosis']
x = df.drop(columns = ['diagnosis'])

In [84]:
x.shape,y.shape

((569, 30), (569,))

In [85]:
#Scaling the data
scaler = StandardScaler()
x = scaler.fit_transform(x)
x


array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]], shape=(569, 30))

In [86]:
#Label Encoding
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y.shape

(569,)

In [87]:
#train  test split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [88]:
x_train.shape , x_test.shape

((455, 30), (114, 30))

In [89]:
y_train.shape , y_test.shape

((455,), (114,))

In [90]:
#coverting array to tensor
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [91]:
x_train.shape , x_test.shape

(torch.Size([455, 30]), torch.Size([114, 30]))

In [92]:
y_train.shape , y_test.shape

(torch.Size([455]), torch.Size([114]))

In [106]:
#defining the model 

class MySimpleNN(nn.Module):
    
    def __init__(self,num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features ,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,x):
        x = self.linear(x)
        x = self.sigmoid(x)
        return x
            
        

In [100]:
#important parameters

learning_rate = 0.01
epochs = 70

In [ ]:
#defining loss
loss = nn.BCELoss()
loss

BCELoss()

In [ ]:
#defining optimizer

optimizer = torch.optim.SGD(model.parameters(),Lr=learning_rate)

In [ ]:
#Training Pipeline

#1. create model
model = MySimpleNN(5)

optimizer = torch.optim.SGD(model.parameters(),Lr=learning_rate)
#all these training steps are done in loop/epochs
for epoch in range(epochs):
    #forward pass
    y_pred = model.forward(x_train)
    #loss calculate
    y_pred = torch.squeeze(y_pred,1)
    loss = loss(y_train,y_pred)
    #backward pass
    loss.backward()
    #parameters update
    optimizer.step()
    
    #zero gradients(reset gradients)
     optimizer.zero_grad()
    #print loss
    
    if epoch == 69:
       print(f"Epoch: {epoch+1} , loss: {loss.item()}")









RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

In [ ]:
y_train.dtype

torch.int64

In [ ]:
model.weights

tensor([[ 0.2651],
        [ 0.4212],
        [ 0.8125],
        [ 0.7618],
        [ 0.4827],
        [ 0.7966],
        [ 0.5802],
        [ 0.1363],
        [ 0.3479],
        [-0.0384],
        [ 0.7200],
        [ 0.1652],
        [ 0.0173],
        [ 0.4486],
        [ 0.4783],
        [ 0.7653],
        [ 0.2472],
        [ 0.1595],
        [ 0.7843],
        [ 0.0741],
        [ 0.3101],
        [ 0.2979],
        [ 0.5166],
        [ 0.0635],
        [ 0.2592],
        [-0.0114],
        [ 0.5847],
        [ 0.4919],
        [ 0.1076],
        [ 0.4843]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.0049], dtype=torch.float64, requires_grad=True)

In [ ]:
#Model Evaluation
with torch.no_grad():
    y_pred_test = model.forward(x_test)
    y_pred_test = (y_pred_test > 0.5).float()
    accuracy = (y_pred_test == y_test).float().mean()
    print((y_pred_test == y_test)
print(f"Test Accuracy: {accuracy.item()*100:.2f}%")

SyntaxError: '(' was never closed (437037586.py, line 6)