In [5]:
import torch

In [6]:
torch.__version__

'2.6.0+cu124'

In [16]:
gpu = torch.cuda.is_available()
print(f"GPU available: {gpu}")
print(f"GPU name: {torch.cuda.get_device_name(0) if gpu else 'No GPU'}")

GPU available: False
GPU name: No GPU


## CREATING A TENSOR

In [ ]:
#using empty tensor -> shows existing memory where values are already present
x = torch.empty(5, 3)
print(x)

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22],
        [2.1715e-18, 5.4931e-05, 1.3108e-08],
        [2.6554e-06, 1.6780e-07, 1.6519e-04]])


In [21]:
#check type
type(x)

torch.Tensor

In [23]:
#using zeros
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
#using ones
x = torch.ones(5, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
#using random
x = torch.rand(5, 3)
x

tensor([[0.6858, 0.9541, 0.3817],
        [0.5718, 0.4613, 0.0470],
        [0.4100, 0.2329, 0.2887],
        [0.5850, 0.6192, 0.6424],
        [0.1841, 0.8861, 0.8310]])

In [31]:
#use of seed
torch.manual_seed(100)
x = torch.rand(5, 3)
x

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [38]:
#using tensor
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [ ]:
#other ways

#arange
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#using linspace
x = torch.linspace(1, 10,10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
#using eye
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [44]:
#using full 
x = torch.full((3, 3), 5)
x

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# TENSOR SHAPES