In [2]:
import torch

/workspaces/SmolArchs/smolly/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
torch.__version__

'2.6.0+cu124'

In [4]:
gpu = torch.cuda.is_available()
print(f"GPU available: {gpu}")
print(f"GPU name: {torch.cuda.get_device_name(0) if gpu else 'No GPU'}")

GPU available: False
GPU name: No GPU


## CREATING A TENSOR

In [5]:
#using empty tensor -> shows existing memory where values are already present
x = torch.empty(5, 3)
print(x)

tensor([[ 1.3117e-19,  2.7864e-10,  8.7336e-23],
        [-8.6010e+14,  7.9215e+07,  8.9459e-23],
        [-9.9730e-15,  4.6088e+07, -1.0156e+30],
        [ 1.2037e-25,  9.0390e-35, -3.1181e-29],
        [ 1.9367e-24,  3.6655e-19, -1.4184e+16]])


In [6]:
#check type
type(x)

torch.Tensor

In [7]:
#using zeros
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
x = torch.ones(5, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using random
x = torch.rand(5, 3)
x

tensor([[0.3233, 0.1755, 0.8946],
        [0.6053, 0.2097, 0.8959],
        [0.2914, 0.1758, 0.6935],
        [0.9364, 0.4839, 0.6043],
        [0.9150, 0.3938, 0.6614]])

In [10]:
#use of seed
torch.manual_seed(100)
x = torch.rand(5, 3)
x

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [11]:
#using tensor
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [12]:
#other ways

#arange
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#using linspace
x = torch.linspace(1, 10,10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
#using eye
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
#using full 
x = torch.full((3, 3), 5)
x

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# TENSOR SHAPES

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[133421053144208, 103795821778304, 103795821779552],
        [103795820283744,               0, 103795820232096]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x.to(torch.float32))

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784]])

# TENSOR DATA TYPES

In [22]:
#find the data type
x.dtype

torch.int64

In [23]:
#assign data type
torch.tensor([[1.0,2.0],[2.0,3.0]], dtype = torch.int32)

tensor([[1, 2],
        [2, 3]], dtype=torch.int32)

In [24]:
#change existing data type
x = torch.tensor([[1.0,2.0],[2.0,3.0]])
x = x.to(torch.int32)
x

tensor([[1, 2],
        [2, 3]], dtype=torch.int32)

# MATHEMATICAL OPERATIONS

In [25]:
# Scalar Operation

torch.manual_seed(100)
x = torch.rand(2,2)
x

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [26]:
#addition
x + 2


tensor([[2.1117, 2.8158],
        [2.2626, 2.4839]])

In [27]:
#subtraction
x - 2

tensor([[-1.8883, -1.1842],
        [-1.7374, -1.5161]])

In [28]:
#multiplication
x * 2

tensor([[0.2233, 1.6317],
        [0.5251, 0.9678]])

In [29]:
#division
x / 2

tensor([[0.0558, 0.4079],
        [0.1313, 0.2419]])

In [30]:
#int division
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [31]:
#modulus
x % 2

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [32]:
#power
x ** 2

tensor([[0.0125, 0.6656],
        [0.0689, 0.2341]])

In [33]:
#element wise operation
a = torch.tensor([6,12])
b = torch.tensor([2,3])

In [34]:
#addition
a + b

tensor([ 8, 15])

In [35]:
#subtraction
a - b

tensor([4, 9])

In [36]:
#multiplication
a * b

tensor([12, 36])

In [37]:
#division
y = a / b
y.to(torch.int32)

tensor([3, 4], dtype=torch.int32)

In [38]:
#power
a ** b

tensor([  36, 1728])

In [39]:
#modulus
a % b

tensor([0, 0])

In [40]:
#abs
a = torch.tensor([[-1, -2],[-3, -4]])
a.abs()

tensor([[1, 2],
        [3, 4]])

In [41]:
#negative
torch.neg(a)

tensor([[1, 2],
        [3, 4]])

In [42]:
#round 
a = torch.tensor([[1.1, 2.2], [3.3, 4.4]])
a.round()

tensor([[1., 2.],
        [3., 4.]])

In [43]:
#ceil
a = torch.tensor([[1.1, 2.2], [3.3, 4.4]])
a.ceil()

tensor([[2., 3.],
        [4., 5.]])

In [44]:
#clamp
a = torch.tensor([[1.1, 2.2], [3.3, 4.4]])
a.clamp(min=2.5, max=3.5)

tensor([[2.5000, 2.5000],
        [3.3000, 3.5000]])

In [45]:
#REDUCTION OPERATION

In [46]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e


tensor([[5., 1., 2.],
        [8., 8., 0.]])

In [47]:
#sum
torch.sum(e)
#sum along columns
torch.sum(e, dim=1)
#sum along rows
torch.sum(e, dim=0)

tensor([13.,  9.,  2.])

In [48]:
#mean
torch.mean(e)
#mean along columns
torch.mean(e, dim=0)
#mean along rows
torch.mean(e, dim=1)

tensor([2.6667, 5.3333])

In [49]:
#median
torch.median(e)

tensor(2.)

In [50]:
#max and min
torch.max(e)
torch.min(e)


tensor(0.)

In [51]:
#product 
torch.prod(e)

tensor(0.)

In [52]:
#standard deviation
torch.std(e)

tensor(3.5214)

In [53]:
#variance
torch.var(e)

tensor(12.4000)

In [54]:
#argmax and argmin
torch.argmax(e)
torch.argmin(e)

tensor(5)

# MATRIX OPERATION

In [55]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])


In [56]:
#matmul
torch.matmul(a,b)

tensor(11)

In [57]:
#dot product
torch.dot(a,b)

tensor(11)

In [58]:
c = torch.tensor([[1,2],[3,4]])

In [59]:
#transpose
torch.transpose(c,0,1)

tensor([[1, 3],
        [2, 4]])

In [60]:
#determinant
torch.det(c.to(dtype=torch.float32))

tensor(-2.)

In [61]:
#inverse
torch.inverse(c.to(dtype=torch.float32))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

# COMPARISSON OPERATORS

In [62]:
#greater than
a > b

tensor([False, False])

In [63]:
#less than
a < b

tensor([True, True])

In [64]:
#equal to
a == b

tensor([False, False])

In [65]:
#not equal to
a != b

tensor([True, True])

In [66]:
#greater than or equal to
a >= b

tensor([False, False])

In [67]:
#less than or equal to
a <= b

tensor([True, True])

# SPECIAL FUNCTIONS

In [68]:
a

tensor([1, 2])

In [69]:
#log
torch.log(a) 


tensor([0.0000, 0.6931])

In [70]:
#exp
torch.exp(a)


tensor([2.7183, 7.3891])

In [71]:
#sqrt
torch.sqrt(a)

tensor([1.0000, 1.4142])

In [72]:
#sigmoid
torch.sigmoid(a)

tensor([0.7311, 0.8808])

In [73]:
#softmax
torch.softmax(a.to(dtype=torch.float32) , dim=0)

tensor([0.2689, 0.7311])

In [74]:
#relu
torch.relu(a)

tensor([1, 2])

In [75]:
a = torch.tensor([[1,2],[3,4]])
device = torch.device('cuda')

In [76]:
a.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

# RESHAPING TENSORS

In [77]:
a = torch.ones(4,4)

In [78]:
#reshape
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [83]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
#permute 
b = torch.rand(2,3,4)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [86]:
#unsqueeze
#image size 
c = torch.rand(226,226,3)

In [87]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [88]:
d = torch.rand(1,20)

In [89]:
#sequeeze
d.squeeze(0).shape

torch.Size([20])